CarsOnline/Controllers/RegisterCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarsOnline.Models;
using CarsOnline.Entities;
using CarsOnline.DAL;

namespace CarsOnline.Controllers
{
    public class RegisterCarController : Controller
    {
        //
        // GET: /RegisterCar/

        public ActionResult Index()
        {
            return View();
        }



        public ActionResult ViewRecord()
        {

            //CarsDTO dto = new CarsDTO();
            //CarsDAO dao = new CarsDAO();
            //dto.Name = "honda";
            //dto.Price = 1200000;
            //ViewBag.car = dto;

            CarsDAO dao = new CarsDAO();

            var login = Session["login1"];
            UserDTO udto= new UserDTO();
            udto.TxtLogin = (string)login;

            List<CarsDTO> list = dao.getRecord(udto);




            return View(list);
        }

        public ActionResult Register(Car model)
        {
            CarsDTO dto = new CarsDTO();

            CarsDAO dao = new CarsDAO();

            if (ModelState.IsValid)
            {
                dto.Name = model.Name;
                dto.Price = model.Price;


                if (model.Price < 1000000)
                {
                    ViewBag.msg = "Too Low Price!!!";
                    return View("Index");
                }
                else
                {

                    var login = Session["login1"];
                    UserDTO dto1 = new UserDTO();
                    dto1.TxtLogin = (string)login;
                    dao.purchaseCar(dto1, dto);
                    return View("Index");

                }


           
            }

            return View("Signup");
            
        }
    }
}

CarsOnline/Views/RegisterCar/Index.cshtml
@model CarsOnline.Models.Car
@{
    ViewBag.Title = "Index";
}


@using (Html.BeginForm("Register","RegisterCar",FormMethod.Post))  
{  
    @Html.ValidationSummary(true)   
    <fieldset>  
        <br />
        <br />
        <legend>Register Your Car:</legend>  
       <br />
       
        <div class="editor-label">  
            @Html.LabelFor(model => model.Name)  
        </div>  
        <div id="editor-field">  
            @Html.EditorFor(model => model.Name)  
            @Html.ValidationMessageFor(model => model.Name)  
        </div>  
  
        <div class="editor-label">  
            @Html.LabelFor(model => model.Price)  
        </div>  
        <div class="editor-field">  
            @Html.EditorFor(model => model.Price)  
            @Html.ValidationMessageFor(model => model.Price)  
        </div>  
  
  
        <div>  
            <br />

       <button type="submit"  id="btnLogin">Register</button>
   
        </div> 
     
        <br />
         
        <div class="container" style="background-color:#f1f1f1">
    <button type="button" onclick="location.href = '/RegisterCar/Index';" class="cancelbtn">Cancel</button>

  </div>
       
    </fieldset>  
}  

CarsOnline/Views/RegisterCar/ViewRecord.cshtml
@model List<CarsOnline.Entities.CarsDTO>

@{
    ViewBag.Title = "ViewRecord";
}

<h1>Your Record is:</h1>

@{
   foreach(var item in Model)
   {
       
       
       <br />
       <div style ="border:1px double; width:300px; height:75px">
           <br />
           <span>Car Name: @item.Name</span> <br />
           <span>Price: @item.Price</span> <br />



       </div>
       
   }
}